spring.cloud.stream:
  bindings:
    input:
      group: ${app.group}
      consumer:
        max-attempts: ${app.max-retries}


spring.cloud.stream.kafka:
  binder:
    brokers: dev-kafka-shared-broker-1.kafka.dev.idap.clgxdata.com
    auto-add-partitions: true
    minPartitionCount: 10
    consumer-properties:
      value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      schema.registry.url: http://dev-kafka-shared-registry.kafka.dev.idap.clgxdata.com:8080
      specific.avro.reader: true

spring:
  redis:
    host: q-s0.redis-instance.services.service-instance-b13eed15-5c09-4666-9a41-5ccb7e3073a8.bosh
    port: 6379
    password: AHPVPj5fhKkDJxYUacZ8BI9Ppg98E9

spring.cloud.stream.kafka.bindings:
  input:
    consumer:
      enableDlq: true
      dlqName: notification-INT-group-dead
      autoCommitOnError: true
      autoCommitOffset: true
      republish-to-dlq: true

spring.cloud.stream.default:
  consumer:
    useNativeEncoding: true

app:
  maxRetries: 3
  group: notification-INT-group
  emailConfig:
    system-email-id: aotf@mailinator.com
    scheduled-email-cron: "0 14 * * * *"

clpservices:
  oauth2:
    client:
      access-token-uri: https://corelogic-np-test.apigee.net/edgemicro-auth/token
      client-id: intersect
      client-secret: Aso4NxMoWR2Y69Ag
    user:
      username: intersect
      password: Aso4NxMoWR2Y69Ag

emailservice.url: http://clp-email-service-int.apps.pcfwtcdev.clgxlabs.io


logging.level.root: log
logging.level.org.springframework.web: warn
logging.level.org.hibernate: error


management:
  endpoints:
    web:
      exposure:
        include: '*'
