spring.cloud.stream.bindings:
  input:
    group: ${app.group}
    consumer:
      max-attempts: ${app.max-retries}
  redis:
    host: ${app.redis-host}


app:
  redis-host: localhost
  maxRetries: 2
  group: notification-group
  emailConfig:
    system-email-id: from@mailinator.com
    scheduled-email-cron: "0 14 * * * *"

server:
  port: 8056


logging.level.root: log
logging.level.org.springframework.web: warn
logging.level.org.hibernate: error

spring:
  devtools:
    livereload:
      port: 35730

clpservices:
  oauth2:
    client:
      access-token-uri: https://corelogic-np-test.apigee.net/edgemicro-auth/token
      client-id: intersect
      client-secret: Aso4NxMoWR2Y69Ag
    user:
      username: intersect
      password: Aso4NxMoWR2Y69Ag
emailservice:
  url: http://clp-email-service-int.apps.pcfwtcdev.clgxlabs.io
health:
  config:
    enabled: false
