spring.cloud.stream.bindings:
  input:
    group: ${application.group}
    consumer:
      max-attempts: ${application.max-retries}
  output:
    producer:
      partition-count: 48

spring:
  cloud:
    stream:
      kafka:
        binder:
          auto-add-partitions: true
          minPartitionCount: 10

spring.cloud.stream.kafka.bindings:
  input:
    consumer:
      enableDlq: true
      dlqName: ${application.dead-letter-topic}
      autoCommitOnError: true
      autoCommitOffset: true
      republish-to-dlq: true

application:
  keyTTL: 60
  keyMapName: member
  deadLetterTopic: member-ingester-dead
  maxRetries: 2
  group: member-group-ingestor

message:
  parent: true
  parentRecordName: member
  childRecordName: member
  collection: false
  parentKey: listingId
  messageKey: messageId


server:
  port: 0
